name: Python Test

on:
  push:
    branches:
      - "feature/*"
      - "fix/*"

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements_test_tools.txt
          pip install -r tests/requirements.txt

      - name: Lint with flake8
        id: flake8
        run: |
          if ! flake8 functions/ --count --max-complexity=10 --max-line-length=100 --statistics; then
            echo "error=Lint check failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Static type checking with mypy
        id: mypy
        run: |
          if ! mypy functions/ --strict; then
            echo "error=Type check failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Run tests with pytest
        id: pytest
        run: |
          if ! pytest tests/ -v; then
            echo "error=Unit tests failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: test results
        if: always()
        run: |
          failed_steps=()
          
          if [[ "${{ steps.flake8.outcome }}" == "failure" ]]; then
            failed_steps+=("Flake8: ${{ steps.flake8.outputs.error }}")
          fi
          
          if [[ "${{ steps.mypy.outcome }}" == "failure" ]]; then
            failed_steps+=("Mypy: ${{ steps.mypy.outputs.error }}")
          fi
          
          if [[ "${{ steps.pytest.outcome }}" == "failure" ]]; then
            failed_steps+=("Pytest: ${{ steps.pytest.outputs.error }}")
          fi
          
          if [ ${#failed_steps[@]} -ne 0 ]; then
            echo "Following checks failed:"
            printf '%s\n' "${failed_steps[@]}"
            exit 1
          fi
